package com.muhammednazeer.bestquotes

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class BestQuotesSQLiteOpenHelper(context: Context) : SQLiteOpenHelper(context, null, null, 1) {
    override fun onCreate(db: SQLiteDatabase?) {
       db!!.execSQL("CREATE TABLE Quote_Categories (" +
       "_id INTEGER PRIMARY KEY," +
       "image_resource_id TEXT," +
       "name TEXT" +
       ")")

        insertQuoteCategory(db, 1, R.drawable.wisdom, "Wisdom")
        insertQuoteCategory(db, 2, R.drawable.knowledge, "Knowledge")
        insertQuoteCategory(db, 3, R.drawable.reading, "Reading")
        insertQuoteCategory(db, 4, R.drawable.impact, "Impact")
        insertQuoteCategory(db, 5, R.drawable.islam, "Islam")
        insertQuoteCategory(db, 6, R.drawable.programming, "Programming")
        insertQuoteCategory(db, 7, R.drawable.self_improvement, "Self Improvement")
        insertQuoteCategory(db, 8, R.drawable.compassion, "Compassion")
        insertQuoteCategory(db, 9, R.drawable.time_management, "Time Management")
        insertQuoteCategory(db, 10, R.drawable.health, "Health")

        //quotes table
        db.execSQL("CREATE TABLE quotes (" +
                "quote TEXT," +
                "category_id INTEGER" + ")")
        
        //Insert quotes to the quote table

        // Wisdom
        insertQuote(db, "No one can make you feel inferior without your consent.", 1)
        insertQuote(db, "It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.", 1)
        insertQuote(db, "The fool doth think he is wise, but the wise man knows himself to be a fool.", 1)
        insertQuote(db, "Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).", 1)
        insertQuote(db, "When someone loves you, the way they talk about you is different. You feel safe and comfortable.", 1)
        insertQuote(db, "Knowing yourself is the beginning of all wisdom.", 1)
        insertQuote(db, "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", 1)
        insertQuote(db, "In a good bookroom you feel in some mysterious way that you are absorbing the wisdom contained in all the books through your skin, without even opening them.", 1)
        insertQuote(db, "It is the mark of an educated mind to be able to entertain a thought without accepting it.", 1)
        insertQuote(db, "The secret of life, though, is to fall seven times and to get up eight times.", 1)
        insertQuote(db, "If you're reading this...\n" +
                "Congratulations, you're alive.\n" +
                "If that's not something to smile about,\n" +
                "then I don't know what is.", 1)
        insertQuote(db, "The best index to a person's character is how he treats people who can't do him any good, and how he treats people who can't fight back.", 1)
        insertQuote(db, "Never let your sense of morals prevent you from doing what is right.", 1)
        insertQuote(db, "The simple things are also the most extraordinary things, and only the wise can see them.", 1)
        insertQuote(db, "There are three things all wise men fear: the sea in storm, a night with no moon, and the anger of a gentle man.", 1)
        insertQuote(db, "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", 1)
        insertQuote(db, "It's a dangerous business, Frodo, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.", 1)
        insertQuote(db, "Angry people are not always wise.", 1)
        insertQuote(db, "You do not write your life with words...You write it with actions. What you think is not important. It is only important what you do.", 1)
        insertQuote(db, "Let no man pull you so low as to hate him.", 1)

        // knowledge
        insertQuote(db, "Real knowledge is to know the extent of one’s ignorance.", 2)
        insertQuote(db, "Knowledge has a beginning but no end.", 2)
        insertQuote(db, "The good life is one inspired by love and guided by knowledge.", 2)
        insertQuote(db, "Be a lifelong student. The more you learn, the more you earn and more self-confidence you will have.", 2)
        insertQuote(db, "An investment in knowledge pays the best interest.", 2)
        insertQuote(db, "Share your knowledge. It is a way to achieve immortality.", 2)
        insertQuote(db, "Knowledge is the life of the mind.", 2)
        insertQuote(db, "Knowledge is like a garden; if it is not cultivated, it cannot be harvested.", 2)
        insertQuote(db, "Beware of false knowledge; it is more dangerous than ignorance.", 2)
        insertQuote(db, "We are drowning in information but starved for knowledge.", 2)
        insertQuote(db, "If you have knowledge, let others light their candles in it.", 2)
        insertQuote(db, "Zeal without knowledge is fire without light.", 2)
        insertQuote(db, "We can have all the knowledge in the world, but it means nothing without the wisdom to know what to do with it.", 2)
        insertQuote(db, "Sharing knowledge occurs when people are genuinely interested in helping one another develop new capacities for action; it is about creating learning processes.", 2)
        insertQuote(db, "There is no wealth like knowledge, no poverty like ignorance.", 2)
        insertQuote(db, "It is not knowledge which should come to you, it is you who should come to the knowledge.", 2)
        insertQuote(db, "Self-confidence results, first, from exact knowledge; second, the ability to impart that knowledge.", 2)
        insertQuote(db, "The possession of knowledge does not kill the sense of wonder and mystery. There is always more mystery.", 2)
        insertQuote(db, "It is impossible for a man to learn what he thinks he already knows.", 2)
        insertQuote(db, "Knowing what you don’t know is more useful than being brilliant.", 2)
        insertQuote(db, "Knowledge is a skyscraper. You can take a shortcut with a fragile foundation of memorization, or build slowly upon a steel frame of understanding.", 2)
        insertQuote(db, "The ultimate test of knowledge is self-transformation. Knowledge is of use only if it brings a profound change in yourself. Make sure that your knowledge is qualitative, not just quantitative. The quality of understanding is important, not the quantity of information.", 2)
        insertQuote(db, "The desire of knowledge, like the thirst of riches, increases ever with the acquisition of it.", 2)
        insertQuote(db, "The true lover of knowledge naturally strives for truth, and is not content with common opinion, but soars with undimmed and unwearied passion till he grasps the essential nature of things. ", 2)
        insertQuote(db, "The construction timeline of knowledge is similar to a skyscraper, too. Takes forever for the hole to be dug and the foundation poured, then the facade appears quickly.", 2)
        insertQuote(db, "Humility will teach you knowledge, arrogance will teach you ignorance. If you think you know it all, you have learned nothing.", 2)
        insertQuote(db, "Doctor Who: You want weapons? We're in a library. Books are the best weapon in the world. This room's the greatest arsenal we could have. Arm yourself!", 2)
        insertQuote(db, "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", 2)
        insertQuote(db, "No thief, however skillful, can rob one of knowledge, and that is why knowledge is the best and safest treasure to acquire.", 2)
        insertQuote(db, "Any fool can know. The point is to understand.", 2)
        insertQuote(db, "The only true wisdom is in knowing you know nothing.", 2)
        insertQuote(db, "Knowledge is of no value unless you put it into practice.", 2)

        // Reading
        insertQuote(db, "Whenever you read a good book, somewhere in the world a door opens to allow in more light.", 3)
        insertQuote(db, "A reader lives a thousand lives before he dies . . . The man who never reads lives only one.", 3)
        insertQuote(db, "Reading is essential for those who seek to rise above the ordinary.", 3)
        insertQuote(db, "You don’t have to burn books to destroy a culture. Just get people to stop reading them.", 3)
        insertQuote(db, "Think before you speak. Read before you think.", 3)
        insertQuote(db, "The reading of all good books is like conversation with the finest (people) of the past centuries.", 3)
        insertQuote(db, "Today a reader, tomorrow a leader.", 3)
        insertQuote(db, "There is more treasure in books than in all the pirate's loot on Treasure Island.", 3)
        insertQuote(db, "One glance at a book and you hear the voice of another person, perhaps someone dead for 1,000 years. To read is to voyage through time.", 3)
        insertQuote(db, "If we encounter a man of rare intellect, we should ask him what books he reads.", 3)
        insertQuote(db, "Show me a family of readers, and I will show you the people who move the world.", 3)
        insertQuote(db, "Reading is a discount ticket to everywhere.", 3)
        insertQuote(db, "No entertainment is so cheap as reading, nor any pleasure so lasting.", 3)
        insertQuote(db, "To acquire the habit of reading is to construct for yourself a refuge from almost all the miseries of life.", 3)
        insertQuote(db, "Despite the enormous quantity of books, how few people read! And if one reads profitably, one would realize how much stupid stuff the vulgar herd is content to swallow every day.", 3)
        insertQuote(db, "Books are good company, in sad times and happy times, for books are people – people who have managed to stay alive by hiding between the covers of a book.", 3)
        insertQuote(db, "There are worse crimes than burning books. One of them is not reading them.", 3)
        insertQuote(db, "I would never read a book if it were possible for me to talk half an hour with the man who wrote it.", 3)
        insertQuote(db, "Reading gives us someplace to go when we have to stay where we are.", 3)
        insertQuote(db, "I think of life as a good book. The further you get into it, the more it begins to make sense.", 3)
        insertQuote(db, "There are many little ways to enlarge your child’s world. Love of books is the best of all.", 3)
        insertQuote(db, "Any book that helps a child to form a habit of reading, to make reading one of his deep and continuing needs, is good for him.", 3)
        insertQuote(db, "Great books help you understand, and they help you feel understood.", 3)
        insertQuote(db, "If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", 3)
        insertQuote(db, "There is a great deal of difference between an eager man who wants to read a book and the tired man who wants a book to read.", 3)
        insertQuote(db, "A book is a dream that you hold in your hand.", 3)
        insertQuote(db, "What about placing it in your bedroom right in front of your bed? You’ll see it when you open your eyes, or right before you’ll close them.", 3)

        // Impact
        insertQuote(db, "Never be complacent about the current steps; don't agree and follow the status quo. Be determined that you are making an indelible impact with great change. Now, dress up and go to make it happen!", 4)
        insertQuote(db, "What people see you do may not be remembered; what they hear you say may be forgotten; but how they feel your intervention in their times of need will forever be remembered.", 4)
        insertQuote(db, "Stand for something. Make your life mean something. Start where you are with what you have. You are enough.", 4)
        insertQuote(db, "The more you offer yourself to make life better for someone, the more you empty yourself of the load of destiny you carry into the world. Serve till you empty all.", 4)
        insertQuote(db, "Death has only one hand glove... so it takes away the body, but leaves behind the impacts. Difference makers live twice; in body and in impacts... The former is temporal but the later lasts long!", 4)
        insertQuote(db, "Everything that the spider needs to make a spider-web is not found in the housefly... it's right there in the spider! Whatever you need to make impacts is in you! Discover yourself and make a difference!", 4)
        insertQuote(db, "We call this a sweet life; to have your impact solutes dissolved in the life of people giving them a solution to their life problems... You can imagine how tasty that could be!", 4)
        insertQuote(db, "Leaders are not worried about the respect and honour they can be given, but the impacts and influence they can give!", 4)
        insertQuote(db, "Time is fleeting. But the impact we make within that time is eternal.", 4)
        insertQuote(db, "When you are called for a great duty because you have been given a great ability, do your very best to leave great footprints no matter what!", 4)
        insertQuote(db, "You can’t be living always in the promise of the clouds; it must rain now. Leave the talking and live by walking… It will yield an indelible impact!", 4)
        insertQuote(db, "Let your little inspire someone greatly and greatly be the reasons for the smiles of someone in little things. Dare to help someone. Dare to be the reasons for somebody’s little smile!", 4)
        insertQuote(db, "Remember, it doesn’t necessarily take too much to make much impact! Remember, it is our little food remains that make the ants get food in season and out of season!", 4)
        insertQuote(db, "Dare to make a noble impact with your noble substance, no matter how big or small it is! Dare to cause a change that will forever be remembered, be it small or big! ", 4)
        insertQuote(db, " Dare to be the real reason for the relief of somebody. Their hearts await your impact! Their joy awaits your ignition! Take a step! Make real impact!", 4)
        insertQuote(db, "If records refuse to be broken, shatter them.", 4)
        insertQuote(db, "Be inspired; you have seen another day! Smile; you have another chance! Take a step; you can do it again! Move; you can't continue like this! Do something for that is all life is about!", 4)
        insertQuote(db, "Impact makers take steps. Impact makers face challenges. Impact makers overcome challenges. Each day is a new day to have a different view of the real purpose why we live. Each day is another chance to take a step towards a great end", 4)
        insertQuote(db, "May it never be a footprint that you shall ever say maybe in May. May it instead be a footprint that you shall do your best and rest the rest!", 4)
        insertQuote(db, "Innovation is the art of creating a better, a more convenient and more comfortable way for the world to pass. Leaders leave footprints everywhere they go. They are impact makers and innovators.", 4)
        insertQuote(db, "Being multifaceted saves you the trouble of hiring a lot of extra people.", 4)
        insertQuote(db, "Power has ruined a lot of people. Powerful people with a grateful spirit always remain humble. Don't allow power to go to your head. Use your power to transform lives and make a difference in this world.", 4)
        insertQuote(db, "Do not ignore a little spark; it can start a wildfire.", 4)
        insertQuote(db, "Never agree to leave the earth without making a great impact in your own life and that of someone else.", 4)



        // Islam
        insertQuote(db, "The richest of the rich is the one who is not a prisoner to greed.", 5)
        insertQuote(db, "The Worst of our faults is our interest in other people’s Faults.", 5)
        insertQuote(db, "If you want to destroy any nation without war, make adultery & nudity common in the next generation.", 5)
        insertQuote(db, "O you who believe! seek help through patience and prayers indeed, Allah is with the patient. – Quran 2:153", 5)
        insertQuote(db, "A person’s tongue can give you the taste of his heart.", 5)
        insertQuote(db, "Control your anger or it will control you.", 5)
        insertQuote(db, "Oh Allah, Give me the strength to distance my self from that which distances me from you.", 5)
        insertQuote(db, "Suicide Bombing is not from Islam Messenger of Allah Said: Indeed whoever (intentionally) Kills Himself, Then Certainly he will be punished in the fire of Hell, wherein he shall dwell forever. Bukharee (5778) & Muslim (109-110)", 5)
        insertQuote(db, "Invite people to Islam Even Without Words. They asked, How? He replied “With Your Manners” Umar Ibn al Khattab Quote", 5)
        insertQuote(db, "The Prophet Muhammad Peace be upon him Said: There will come a time when holding on to your religion will be like holding burning coal. – Sunan al-Tirmidhi: 3056", 5)
        insertQuote(db, "What is Jihad? smiling in the Tough moment is Jihad. keeping Patience in hard times is Jihad. Struggling for the good deed is jihad. taking care of old parents in a loving way is jihad. forgiving is jihad. Jihad is not what the media shows but what the Quran Says to strive and to Struggle!", 5)
        insertQuote(db, "Indeed, that is My Path – perfectly straight. So follow it and do not follow other ways, for they will lead you away from His Way. This is what He has commanded you, so perhaps you will be conscious of Allah (God). Quran 6:153", 5)
        insertQuote(db, "When you seek Dunya (world), you lose the Hereafter. When you seek the Hereafter, you gain both Dunya (world) and the Hereafter. Which is the wiser transaction?", 5)
        insertQuote(db, "Speak only when your words are more beautiful than the silence", 5)
        insertQuote(db, "Give love in secret by praying for one another.", 5)
        insertQuote(db, "Everyone who is taken by death asks for more time, while everyone who still has time makes excuses for procrastination.", 5)
        insertQuote(db, "Sell this life for the next and you win both of them. Sell the next life for this and you lose both of them.", 5)
        insertQuote(db, "If only we were greedy for the Hereafter like we are greedy for the Dunya (world).", 5)
        insertQuote(db, "When you see a person who has been given more than you in money and beauty, then look to those who have been given less.", 5)
        insertQuote(db, "The world is 3 days: As for yesterday, it has vanished along with all that was in it. As for tomorrow, you may never see it. As for today, it is yours, so work on it.", 5)
        insertQuote(db, "Dear Muslimah…\n" +
                "\n" +
                "Don’t be proud of every guy wants you, cheap items have many buyers be a rare stone that only the pious can afford you, reach and get you in a Halal relationship (Nikkah)", 5)
        insertQuote(db, "When we repair our relationship with Allah, He repairs everything else for us.", 5)
        insertQuote(db, "No matter what your physical appearance, when you have kindness in your heart, You’re the most beautiful person in the world.", 5)
        insertQuote(db, "Some of the toughest ayat in the Quran has Allah’s name AR-RAHMAN in them to make it clear that just because Allah is the most Merciful, It Doesn’t mean he’s not going to carry out Justice.", 5)
        insertQuote(db, "Sujood. A love story no one will understand except those who pray.", 5)
        insertQuote(db, "Allah understands our prayers even when we can’t find the words to say them.", 5)
        insertQuote(db, "You Cannot Delete your internet history from ALLAH.", 5)
        insertQuote(db, "Beware of being found where Allah prohibited you from. and beware of being absent from where Allah commanded you to be.", 5)
        insertQuote(db, "People of ALHAMDULILAH don’t have time to complain.", 5)
        insertQuote(db, "There is no moving creature on earth but its sustenance depends on God. and he knows where it lives and where it rests. Every thing is in a Clear book", 5)
        insertQuote(db, "Take Account of yourselves before you are taken to account. Weigh your deeds before they are weighed. Umar ibn Al-Khattab.", 5)
        insertQuote(db, "There is no Islam without unity, no unity without leadership, and no leadership without obedience.” – Umar ibn al-Khattab (RA)", 5)
        insertQuote(db, "Our success and failure are in the hands of Allah, not people. if he is with you, no one can harm you.", 5)

        // Programming
        insertQuote(db, "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live", 6)
        insertQuote(db, "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.", 6)
        insertQuote(db, "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", 6)
        insertQuote(db, "The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly. A programmer is ideally an essayist who works with traditional aesthetic and literary forms as well as mathematical concepts, to communicate the way that an algorithm works and to convince a reader that the results will be correct.", 6)
        insertQuote(db, "I'm not a great programmer; I'm just a good programmer with great habits.", 6)
        insertQuote(db, "Truth can only be found in one place: the code.", 6)
        insertQuote(db, "Give a man a program, frustrate him for a day.\n" +
                "Teach a man to program, frustrate him for a lifetime.", 6)
        insertQuote(db, "How you look at it is pretty much how you'll see it", 6)
        insertQuote(db, "A language that doesn't affect the way you think about programming is not worth knowing.", 6)
        insertQuote(db, "A language that doesn't affect the way you think about programming is not worth knowing.", 6)
        insertQuote(db, "On two occasions, I have been asked [by members of Parliament], 'Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?' I am not able to rightly apprehend the kind of confusion of ideas that could provoke such a question.", 6)
        insertQuote(db, "Walking on water and developing software from a specification are easy if both are frozen.", 6)
        insertQuote(db, "The most disastrous thing that you can ever learn is your first programming language.", 6)
        insertQuote(db, "The computer programmer is a creator of universes for which he alone is the lawgiver. No playwright, no stage director, no emperor, however powerful, has ever exercised such absolute authority to arrange a stage or field of battle and to command such unswervingly dutiful actors or troops.", 6)
        insertQuote(db, "Perl – The only language that looks the same before and after RSA encryption.", 6)
        insertQuote(db, "The most important property of a program is whether it accomplishes the intention of its user.", 6)
        insertQuote(db, "When they first built the University of California at Irvine they just put the buildings in. They did not put any sidewalks, they just planted grass. The next year, they came back and put the sidewalks where the trails were in the grass. Perl is just that kind of language. It is not designed from first principles. Perl is those sidewalks in the grass.", 6)
        insertQuote(db, "A computer is like a violin. You can imagine a novice trying ﬁrst a phonograph and then a violin. The latter, he says, sounds terrible. That is the argument we have heard from our humanists and most of our computer scientists. Computer programs are good, they say, for particular purposes, but they aren’t ﬂexible. Neither is a violin, or a typewriter, until you learn how to use it.", 6)
        insertQuote(db, "Object-oriented programming offers a sustainable way to write spaghetti code. It lets you accrete programs as a series of patches.", 6)
        insertQuote(db, "Remember that code is really the language in which we ultimately express the requirements. We may create languages that are closer to the requirements. We may create tools that help us parse and assemble those requirements into formal structures. But we will never eliminate necessary precision—so there will always be code.", 6)
        insertQuote(db, "Without requirements or design, programming is the art of adding bugs to an empty text file.", 6)
        insertQuote(db, "A good programmer is someone who always looks both ways before crossing a one-way street.", 6)
        insertQuote(db, "In order to understand recursion, one must first understand recursion.", 6)
        insertQuote(db, "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. ", 6)
        insertQuote(db, "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.", 6)
        insertQuote(db, "Fix the cause, not the symptom.", 6)
        insertQuote(db, "Optimism is an occupational hazard of programming: feedback is the treatment.", 6)
        insertQuote(db, "When to use iterative development? You should use iterative development only on projects that you want to succeed.", 6)
        insertQuote(db, "In order to be irreplaceable, one must always be different", 6)
        insertQuote(db, "First, solve the problem. Then, write the code.", 6)
        insertQuote(db, "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.", 6)
        insertQuote(db, "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.", 6)

        // Self Improvement
        insertQuote(db, "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", 7)
        insertQuote(db, "Become addicted to constant and never-ending self-improvement.", 7)
        insertQuote(db, "Always dream and shoot higher than you know you can do. Do not bother just to be better than your contemporaries or predecessors. Try to be better than yourself.", 7)
        insertQuote(db, "No matter who you are, no matter what you did, no matter where you’ve come from, you can always change, become a better version of yourself.", 7)
        insertQuote(db, "Formal education will make you a living; self-education will make you a fortune.", 7)
        insertQuote(db, "He who conquers himself is the mightiest warrior.", 7)
        insertQuote(db, "It is not as much about who you used to be, as it is about who you choose to be.", 7)
        insertQuote(db, "A proud man is always looking down on things and people; and, of course, as long as you are looking down, you cannot see something that is above you.", 7)
        insertQuote(db, "Make the most of yourself....for that is all there is of you.", 7)
        insertQuote(db, "Once we accept our limits, we go beyond them.", 7)
        insertQuote(db, "If you try anything, if you try to lose weight, or to improve yourself, or to love, or to make the world a better place, you have already achieved something wonderful, before you even begin. Forget failure. If things don't work out the way you want, hold your head up high and be proud. And try again. And again. And again!", 7)
        insertQuote(db, "When you see a good person, think of becoming like her/him. When you see someone not so good, reflect on your own weak points.", 7)
        insertQuote(db, "I like to listen. I have learned a great deal from listening carefully. Most people never listen.", 7)
        insertQuote(db, "She hoped to be wise and reasonable in time; but alas! Alas! She must confess to herself that she was not wise yet.", 7)
        insertQuote(db, "The mind is just like a muscle - the more you exercise it, the stronger it gets and the more it can expand.", 7)
        insertQuote(db, "We do not get to choose how we start out in life. We do not get to choose the day we are born or the family we are born into, what we are named at birth, what country we are born in, and we do not get to choose our ancestry. All these things are predetermined by the Creator. By the time you are old enough to start making decisions for yourself, a lot of things in your life are already in place. It’s important, therefore, that you focus on the future, the only thing that you can change.", 7)
        insertQuote(db, "Excellence is not a destination; it is a continuous journey that never ends.", 7)
        insertQuote(db, "Employ your time in improving yourself by other men’s writings so that you shall come easily by what others have laboured hard for.", 7)
        insertQuote(db, "Don’t compare yourself to others. Compare yourself to the person from yesterday.", 7)
        insertQuote(db, "When we strive to become better than we are, everything around us becomes better too.", 7)
        insertQuote(db, "There is no challenge more challenging than the challenge to improve yourself.", 7)
        // Compassion
        insertQuote(db, "All I ever wanted was to reach out and touch another human being not just with my hands but with my heart.", 8)
        insertQuote(db, "Compassion is the basis of morality.", 8)
        insertQuote(db, "No one has ever become poor by giving.", 8)
        insertQuote(db, "For me, I am driven by two main philosophies: know more today about the world than I knew yesterday and lessen the suffering of others. You'd be surprised how far that gets you.", 8)
        insertQuote(db, "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", 8)
        insertQuote(db, "There is no exercise better for the heart than reaching down and lifting people up.", 8)
        insertQuote(db, "Too often we underestimate the power of a touch, a smile, a kind word, a listening ear, an honest compliment, or the smallest act of caring, all of which have the potential to turn a life around.", 8)
        insertQuote(db, "It is an absolute human certainty that no one can know his own beauty or perceive a sense of his own worth until it has been reflected back to him in the mirror of another loving, caring human being.", 8)
        insertQuote(db, "Our task must be to free ourselves... by widening our circle of compassion to embrace all living creatures and the whole of nature and it's beauty.", 8)
        insertQuote(db, "I have no idea what's awaiting me, or what will happen when this all ends. For the moment I know this: there are sick people and they need curing.", 8)
        insertQuote(db, "No act of kindness, no matter how small, is ever wasted.", 8)
        insertQuote(db, "It does not matter how long you are spending on the earth, how much money you have gathered or how much attention you have received. It is the amount of positive vibration you have radiated in life that matters.", 8)
        insertQuote(db, "There is a nobility in compassion, a beauty in empathy, a grace in forgiveness.", 8)
        insertQuote(db, "Use your voice for kindness, your ears for compassion, your hands for charity, your mind for truth, and your heart for love.", 8)
        insertQuote(db, "Compassion is an action word with no boundaries.", 8)
        insertQuote(db, "Compassion is at the heart of every little thing we do. It is the dearest quality we possess. Yet all too often it can be cast aside with consequences too tragic to speak of. To lose our compassion, we lose what it is to be human.", 8)
        insertQuote(db, "Let our hearts be stretched out in compassion toward others, for everyone is walking his or her own difficult path.", 8)
        insertQuote(db, "Compassion is to look beyond your own pain, to see the pain of others.", 8)
        insertQuote(db, "Our sorrows and wounds are healed only when we touch them with compassion.", 8)
        insertQuote(db, "It is not enough to be compassionate. You must act.", 8)
        insertQuote(db, "Clothe yourself with compassion, kindness, humility, gentleness, and patience.", 8)

        // Time Management
        insertQuote(db, "Time is the school in which we learn, time is the fire in which we burn.", 9)
        insertQuote(db, "Time is what we want most, but what we use worst.", 9)
        insertQuote(db, "The common man is not concerned about the passage of time, the man of talent is driven by it.", 9)
        insertQuote(db, "Time = life; therefore, waste your time and waste of your life, or master your time and master your life.", 9)
        insertQuote(db, "Don’t be fooled by the calendar. There are only as many days in the year as you make use of. One man gets only a week’s value out of a year while another man gets a full year’s value out of a week.", 9)
        insertQuote(db, "Ordinary people think merely of spending time. Great people think of using it.", 9)
        insertQuote(db, "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. It is wonderful how much can be done if we are always doing.", 9)
        insertQuote(db, "This time, like all times, is a very good one, if we but know what to do with it.", 9)
        insertQuote(db, "If you want to make good use of your time, you’ve got to know what’s most important and then give it all you’ve got.", 9)
        insertQuote(db, "It’s not enough to be busy, so are the ants. The question is, what are we busy about?", 9)
        insertQuote(db, "Take care of the minutes and the hours will take care of themselves.", 9)
        insertQuote(db, "Never let yesterday use up today.", 9)
        insertQuote(db, "Realize that now, in this moment of time, you are creating. You are creating your next moment. That is what’s real.", 9)
        insertQuote(db, "The time for action is now. It’s never too late to do something.", 9)
        insertQuote(db, "You cannot do a kindness too soon, for you never know how soon it will be too late.", 9)
        insertQuote(db, "Whether it’s the best of times or the worst of times, it’s the only time we’ve got.", 9)
        insertQuote(db, "This is the beginning of a new day.\n" +
                "God has given me this day to use as I will.\n" +
                "I can waste it or use it for good.\n" +
                "What I do today is important, because\n" +
                "I am exchanging a day of my life for it.\n" +
                "When tomorrow comes,\n" +
                "this day will be gone forever,\n" +
                "leaving in its place something\n" +
                "that I have traded for it.\n" +
                "I want it to be gain, not loss;\n" +
                "good not evil; success not failure;\n" +
                "in order that I shall not regret\n" +
                "the price I paid for it.", 9)
        insertQuote(db, "Lost wealth may be replaced by industry, lost knowledge by study, lost health by temperance or medicine, but lost time is gone forever.", 9)
        insertQuote(db, "Money, I can only gain or lose. But time I can only lose. So, I must spend it carefully.", 9)
        insertQuote(db, "One thing you can’t recycle is wasted time.", 9)
        insertQuote(db, "All that really belongs to us is time; even he who has nothing else has that.", 9)
        insertQuote(db, "Until you value yourself, you will not value your time. Until you value your time, you will not do anything with it.", 9)
        insertQuote(db, "Your greatest resource is your time.", 9)
        insertQuote(db, "Time is at once the most valuable and the most perishable of all our possessions.", 9)
        insertQuote(db, "Time is really the only capital that any human being has, and the only thing he can’t afford to lose.", 9)
        insertQuote(db, "Those who make the worse use of their time are the first to complain of its shortness.", 9)
        insertQuote(db, "Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent. Be careful lest you let other people spend it for you.", 9)
        insertQuote(db, "The bad news is time flies. The good news is you’re the pilot.", 9)
        insertQuote(db, "Never leave ’till tomorrow which you can do today.", 9)
        insertQuote(db, "The surest way to be late is to have plenty of time.", 9)
        insertQuote(db, "I am definitely going to take a course on time management… just as soon as I can work it into my schedule.", 9)

        // Health
        insertQuote(db, "He who has health has hope; and he who has hope has everything. Arabian proverb", 10)
        insertQuote(db, "It is health that is real wealth and not pieces of gold and silver.", 10)
        insertQuote(db, "Keep your vitality. A life without health is like a river without water.", 10)
        insertQuote(db, "A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.", 10)
        insertQuote(db, "Happiness is the highest form of health. ", 10)
        insertQuote(db, "The greatest of follies is to sacrifice health for any other kind of happiness.", 10)
        insertQuote(db, "The more you understand yourself, the more silence there is, the healthier you are.", 10)
        insertQuote(db, "Doctors won’t make you healthy. Nutritionists won’t make you slim. Teachers won’t make you smart. Gurus won’t make you calm. Mentors won’t make you rich. Trainers won’t make you fit. Ultimately, you have to take responsibility. Save yourself.", 10)
        insertQuote(db, "When the heart is at ease, the body is healthy. Chinese proverb", 10)
        insertQuote(db, "In a disordered mind, as in a disordered body, soundness of health is impossible. ", 10)
        insertQuote(db, "Your health is what you make of it. Everything you do and think either adds to the vitality, energy and spirit you possess or takes away from it. ", 10)
        insertQuote(db, "Give a man health and a course to steer, and he’ll never stop to trouble about whether he’s happy or not.", 10)
        insertQuote(db, "The scientific truth may be put quite briefly; eat moderately, having an ordinary mixed diet, and don’t worry. ", 10)
        insertQuote(db, "I believe that the greatest gift you can give your family and the world is a healthy you.", 10)
        insertQuote(db, "Moderation. Small helpings. Sample a little bit of everything. These are the secrets of happiness and good health.", 10)
        insertQuote(db, "The secret of health for both mind and body is not to mourn for the past, not to worry about the future, or not to anticipate troubles, but to live in the present moment wisely and earnestly.", 10)
        insertQuote(db, "Health is the thing that makes you feel that now is the best time of year. ", 10)
        insertQuote(db, "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", 10)
        insertQuote(db, "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", 10)
        insertQuote(db, "I have chosen to be happy because it is good for my health.", 10)
        insertQuote(db, "Prevention is better than cure. ", 10)
        insertQuote(db, "I am confident that nobody will accuse me of selfishness if I ask to spend time, while I am still in good health, with my family, my friends and also with myself. ", 10)
        insertQuote(db, "Love is not as important as good health. You cannot be in love if you’re not healthy. You can’t appreciate it. ", 10)
        insertQuote(db, "Cheerfulness is the best promoter of health and is as friendly to the mind as to the body. ", 10)
        insertQuote(db, "Embrace and love your body. It’s the most amazing thing you will ever own. ", 10)
        insertQuote(db, "The higher your energy level, the more efficient your body. The more efficient your body, the better you feel and the more you will use your talent to produce outstanding results. ", 10)
        insertQuote(db, "After these two, Dr. Diet and Dr. Quiet, Dr. Merriman is requisite to preserve health. ", 10)
        insertQuote(db, "Good health is not something we can buy. However, it can be an extremely valuable savings account.", 10)
        insertQuote(db, "Many people treat their bodies as if they were rented from Hertz – something they are using to get around in but nothing they genuinely care about understanding.", 10)
        insertQuote(db, "There is something in sickness that breaks down the pride of manhood. ", 10)
        insertQuote(db, "Sickness always brings the soul nearer to God.", 10)
        insertQuote(db, "If you have health, you probably will be happy, and if you have health and happiness, you have all the wealth you need, even if it is not all you want.", 10)
        insertQuote(db, "Diseases of the soul are more dangerous and more numerous than those of the body. ", 10)
    }
    private fun insertQuote(db: SQLiteDatabase?, quote: String, categoryId: Int){
        val contentValues = ContentValues()
        contentValues.put("quote", quote)
        contentValues.put("category_id", categoryId)
        db!!.insert("quotes", null, contentValues)
    }
    private fun insertQuoteCategory(db: SQLiteDatabase? , id: Int, resourceId: Int, name: String ){
        val contentValues = ContentValues()
        contentValues.put("_id", id)
        contentValues.put("image_resource_id", resourceId)
        contentValues.put("name", name)
        db!!.insert("Quote_Categories", null, contentValues)

    }

    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        //TODO("Not yet implemented")
    }
}